// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import Header from './components/header';
// import { Provider, useSelector } from 'react-redux';
// import { store } from "./store"

// // Load fonts
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const isAdminLoggedIn = useSelector((state) => state.admin.isLoggedIn);
//   const isUserLoggedIn = useSelector((state) => state.user.isLoggedIn);
//   console.log("isAdminLoggedIn", isAdminLoggedIn);
//   console.log("isUserLoggedIn", isUserLoggedIn);

//   return (  
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//       <Provider store={store}>
//         <Header /> {/* Header will be present on every page */}
//         <main style={{ marginTop: '64px' }}> {/* Adjust the margin based on header height */}
//           {children} {/* Next.js renders the specific page content here */}
//         </main>
//         </Provider>
//       </body>
//     </html>
//   );
// }


// // *************************Updated Layout for the use of redux *************************************//
// // src/app/layout.tsx
'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from './components/header';
import { Provider } from 'react-redux';
import { store } from "./store/index";
import ClientProvider from "./components/ClientProvider"; // Import the ClientProvider

// Load fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
          <Header /> {/* Header present on every page */}
          <ClientProvider> {/* Wrap content with ClientProvider */}
            <main style={{ marginTop: '64px' }}>
              {children}
            </main>
          </ClientProvider>
        </Provider>
      </body>
    </html>
  );
}
